name: publish

on:
  push:
    branches:
    - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish image
      run: |
        docker build . --tag ghcr.io/curtisy1/photon-docker:latest
        docker push ghcr.io/curtisy1/photon-docker:latest